'use client'
// =============================================================================
// Complete Project Report — print-optimized, single-document view of every
// dashboard section in ControlLens. PM navigates to /dashboard/report, clicks
// "Print Report" (or Ctrl+P) → Save as PDF → send to client.
//
// Sections (in order):
//   1. Executive Summary  — Key Dates, Durations, KPI tiles, Health
//   2. Critical Path Drivers
//   3. Longest Path
//   4. Multiple Float Paths (ControlLens) — ranked driving chains  [Day 10]
//   5. Construction Sequence Problems
//   6. Long Lead Items
//   7. Submittals (Submit + Review pairs)
//   8. Key Milestones
//   9. Two-Week Lookahead
//  10. Activities with No Logic Ties
//  11. Earned Value  — if data entered
//  A1–A3. Appendix — In Progress / Not Started / Finished activities
//
// Every page footer shows "Generated by ControlLens · {date}" via @page CSS.
// =============================================================================

import { useEffect, useState, useMemo } from 'react'
import Link from 'next/link'
import {
  getActiveProject, getActiveVersion, subscribeToProjects,
  addCalendarDays,
  Project, ScheduleVersion,
} from '@/lib/projectStore'
import { evmCumulative, fmtDollars, fmtRatio as fmtEvmRatio } from '@/lib/evm'
import { analyzeMultipleFloatPaths } from '@/lib/multipleFloatPaths'

export default function ReportPage() {
  const [project, setProject] = useState<Project | null>(null)
  const [version, setVersion] = useState<ScheduleVersion | null>(null)

  useEffect(() => {
    refresh()
    const unsub = subscribeToProjects(refresh)
    return unsub
  }, [])

  function refresh() {
    const p = getActiveProject()
    setProject(p)
    setVersion(p ? getActiveVersion(p) : null)
  }

  if (!project || !version) {
    return (
      <div className="flex items-center justify-center h-full bg-slate-50 p-6">
        <div className="bg-white border border-slate-200 rounded-xl p-8 max-w-md text-center">
          <div className="text-3xl mb-3">📄</div>
          <div className="font-bold text-slate-800 mb-2">No active project</div>
          <div className="text-sm text-slate-500 mb-4">
            Pick a project from the sidebar, then return here to generate a report.
          </div>
          <Link href="/dashboard" className="inline-block bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold px-4 py-2 rounded-lg">
            Back to Dashboard
          </Link>
        </div>
      </div>
    )
  }

  return <ReportContent project={project} version={version} />
}

function ReportContent({ project, version }: { project: Project; version: ScheduleVersion }) {
  const a = version.analysis || {}
  const generatedAt = new Date().toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: 'numeric', minute: '2-digit',
  })

  // ---------- derived data ----------
  const manualNtp = project.contractDates?.ntp || undefined
  const manualOriginal = project.contractDates?.originalContractCompletion || undefined
  const manualSubst = project.contractDates?.substantialCompletion || undefined
  const timeExt = version.versionDates?.timeExtensionDays ?? 0
  const manualRevised = version.versionDates?.revisedContractCompletion || undefined
  const manualDataDate = version.versionDates?.manualDataDate || undefined
  const revisedComp = manualRevised || (manualOriginal ? addCalendarDays(manualOriginal, timeExt) : undefined)

  const dataDate = manualDataDate || a.dataDate || version.dataDate || version.uploadedAt
  const ntp = manualNtp || a.projectStartDate || dataDate
  const contractEnd = manualOriginal || a.contractEnd
  const projectedEnd = a.projectedEnd || contractEnd
  const substantialXER = a.substantialCompletionDate
  const finalCompletion = a.finalCompletionDate || projectedEnd

  const totalActivities = num(a.totalActivities, 0)
  const complete = num(a.complete, 0)
  const inProgress = num(a.inProgress, 0)
  const notStarted = num(a.notStarted, 0)
  const healthScore = num(a.healthScore, 0)
  const condition = a.condition || deriveCondition(healthScore)
  const delayDays = num(a.delayDays, 0)
  const negativeFloat = num(a.negativeFloat, 0)

  // Days behind contract — manual revised vs projected (matches dashboard)
  let daysBehind = 0
  if (revisedComp && projectedEnd) {
    const cd = new Date(revisedComp)
    const pd = new Date(projectedEnd)
    if (!isNaN(cd.getTime()) && !isNaN(pd.getTime())) {
      const cu = Date.UTC(cd.getFullYear(), cd.getMonth(), cd.getDate())
      const pu = Date.UTC(pd.getFullYear(), pd.getMonth(), pd.getDate())
      daysBehind = Math.round((pu - cu) / 86_400_000)
    }
  }

  const workComplete = num(a.workCompletePct, 0)
  const constructionCount = num(a.constructionActivityCount, 0)
  const completedAtThreshold = num(a.completedAtThreshold, 0)

  const criticalDrivers = arr(a.criticalDrivers).slice(0, 50)
  const outOfSequence = arr(a.outOfSequence).slice(0, 50)
  const longLeadItems = arr(a.longLeadItems)
  const submittals = arr(a.submittals)
  const milestones = arr(a.milestones)
  const twoWeek = arr(a.twoWeekLookahead).slice(0, 50)
  const notStartedList = arr(a.notStartedActivities).slice(0, 100)
  const finishedList = arr(a.finishedActivities).slice(0, 100)
  const inProgressList = arr(a.inProgressActivities)
  const longestPath = arr(a.longestPathActivities).slice(0, 100)
  const noTies = arr(a.noTies).slice(0, 50)

  // Day 10 — Multiple Float Paths (ControlLens). Runs on allTasksForPaths
  // (populated by analyzeXER). Defaults to threshold=5 days, top 5 paths.
  // Older versions uploaded before this field existed will get empty result.
  const multiPathsResult = (() => {
    try {
      return analyzeMultipleFloatPaths(arr(a.allTasksForPaths), 5, 5)
    } catch {
      return null
    }
  })()

  const risksCritical = num(a.risksCritical, 0)
  const risksHigh = num(a.risksHigh, 0)
  const risksMedium = num(a.risksMedium, 0)
  const risksTotal = risksCritical + risksHigh + risksMedium

  const longLeadAtRisk = num(a.longLeadAtRisk, 0)
  const longLeadTotal = num(a.longLeadTotal, longLeadItems.length)

  const evm = project.evm

  return (
    <>
      {/* Print-only CSS — controls page size, margins, hides interactive UI */}
      <style jsx global>{`
        @media print {
          @page {
            size: letter;
            margin: 0.55in 0.5in 0.7in 0.5in;
            @bottom-center {
              content: "Generated by ControlLens  ·  app.control-lens.com  ·  Page " counter(page) " of " counter(pages);
              font-family: ui-sans-serif, system-ui, sans-serif;
              font-size: 8pt;
              color: #64748b;
            }
          }
          .no-print { display: none !important; }
          .print-page-break { page-break-before: always; }
          .print-avoid-break { page-break-inside: avoid; }
          body { background: white !important; }
          .report-shell { background: white !important; }
        }
        .report-shell { font-family: ui-sans-serif, system-ui, -apple-system, sans-serif; }
        .report-shell table { border-collapse: collapse; }
        .report-shell thead th {
          background: #f1f5f9;
          font-size: 9pt;
          font-weight: 700;
          color: #334155;
          text-align: left;
          padding: 5px 8px;
          border-bottom: 1px solid #cbd5e1;
        }
        .report-shell tbody td {
          padding: 4px 8px;
          font-size: 9pt;
          color: #1e293b;
          border-bottom: 1px solid #f1f5f9;
          vertical-align: top;
        }
        .report-shell tbody tr:nth-child(even) { background: #fafbfc; }
      `}</style>

      {/* Action bar — visible on screen, hidden when printing */}
      <div className="no-print sticky top-0 z-50 bg-white border-b border-slate-200 px-6 py-3 flex items-center justify-between shadow-sm">
        <div>
          <div className="font-bold text-slate-900 text-sm">Complete Project Report</div>
          <div className="text-xs text-slate-500">{project.name} · {project.projectId || '—'} · {version.versionLabel || version.fileName}</div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => window.print()}
            className="bg-blue-600 hover:bg-blue-700 text-white text-sm font-bold px-4 py-2 rounded-lg flex items-center gap-2"
          >
            🖨 Print / Save as PDF
          </button>
          <Link href="/dashboard" className="text-sm font-semibold text-slate-600 hover:text-slate-900 px-3 py-2">
            ← Back
          </Link>
        </div>
      </div>

      <div className="report-shell bg-slate-50 min-h-screen py-6 px-4">
        <div className="max-w-[8.5in] mx-auto bg-white shadow-sm border border-slate-200">

          {/* ============================================ COVER PAGE ============================================ */}
          <section className="px-12 py-16" style={{ minHeight: '10.5in' }}>
            <div className="flex flex-col items-center justify-center h-full">
              {/* Logo */}
              <div className="flex items-center gap-3 mb-12">
                <ControlLensLogo />
                <div className="text-3xl font-extrabold tracking-tight">
                  <span className="text-slate-800">Control</span><span className="text-blue-600">Lens</span>
                </div>
              </div>

              <div className="text-center mt-8 mb-16">
                <div className="text-xs uppercase tracking-[0.3em] text-slate-500 font-bold mb-3">Complete Project Report</div>
                <div className="text-4xl font-bold text-slate-900 leading-tight mb-2 max-w-2xl">
                  {project.name}
                </div>
                <div className="text-lg text-slate-600 font-mono">{project.projectId || '—'}</div>
              </div>

              {/* Key data summary on cover */}
              <div className="grid grid-cols-2 gap-x-12 gap-y-3 mt-8 w-full max-w-md">
                <CoverRow label="Schedule Version" value={version.versionLabel || version.fileName} />
                <CoverRow label="Data Date" value={fmtDate(dataDate)} />
                <CoverRow label="Contract Start (NTP)" value={fmtDate(ntp)} />
                <CoverRow label="Contract End" value={fmtDate(contractEnd)} />
                {revisedComp && <CoverRow label="Revised Completion" value={fmtDate(revisedComp)} />}
                <CoverRow label="Projected End" value={fmtDate(projectedEnd)} />
                <CoverRow label="Health Score" value={`${healthScore} / 100`} />
                <CoverRow label="Condition" value={condition} />
                {project.owner && <CoverRow label="Owner / Client" value={project.owner} />}
                {version.context?.gc && <CoverRow label="General Contractor" value={version.context.gc} />}
              </div>

              <div className="mt-auto pt-16 text-center text-xs text-slate-400">
                Generated by ControlLens · {generatedAt}<br />
                app.control-lens.com
              </div>
            </div>
          </section>

          {/* ============================================ EXECUTIVE SUMMARY ============================================ */}
          <section className="print-page-break px-10 py-10">
            <SectionHeading num="1" title="Executive Summary" />

            {/* Key Dates */}
            <SubHeading>Key Dates</SubHeading>
            <table className="w-full mb-6">
              <thead>
                <tr>
                  <th style={{ width: '30%' }}>Milestone</th>
                  <th style={{ width: '25%' }}>Date</th>
                  <th>Source</th>
                </tr>
              </thead>
              <tbody>
                <tr><td><b>NTP / Contract Start</b></td><td>{fmtDate(ntp)}</td><td>{manualNtp ? 'Entered manually' : 'From XER'}</td></tr>
                <tr><td><b>Original Contract Completion</b></td><td>{fmtDate(contractEnd)}</td><td>{manualOriginal ? 'Entered manually' : 'From XER'}</td></tr>
                <tr><td><b>Revised Contract Completion</b></td><td>{fmtDate(revisedComp)}</td><td>{manualRevised ? 'Manual override' : timeExt > 0 ? `Original + ${timeExt} days` : 'No time extension'}</td></tr>
                <tr><td><b>Substantial Completion (Manual)</b></td><td>{fmtDate(manualSubst)}</td><td>Per contract</td></tr>
                <tr><td><b>Substantial Completion (XER)</b></td><td>{fmtDate(substantialXER)}</td><td>Detected from XER</td></tr>
                <tr><td><b>Final Completion (XER)</b></td><td>{fmtDate(finalCompletion)}</td><td>Detected from XER</td></tr>
                <tr><td><b>Data Date</b></td><td>{fmtDate(dataDate)}</td><td>{manualDataDate ? 'Manual entry' : 'From XER'}</td></tr>
                <tr><td><b>Projected End (Forecast)</b></td><td>{fmtDate(projectedEnd)}</td><td>{daysBehind > 0 ? `+${daysBehind} days vs revised` : 'On contract'}</td></tr>
              </tbody>
            </table>

            {/* Health */}
            <SubHeading>Schedule Health</SubHeading>
            <div className="grid grid-cols-4 gap-3 mb-6">
              <Stat label="Health Score" value={`${healthScore}/100`} />
              <Stat label="Condition" value={condition} />
              <Stat label="Days Behind Contract" value={daysBehind > 0 ? `+${daysBehind}` : '0'} />
              <Stat label="Work Complete" value={`${Math.round(workComplete)}%`} />
            </div>

            {/* Activity counts */}
            <SubHeading>Activity Counts</SubHeading>
            <div className="grid grid-cols-5 gap-3 mb-6">
              <Stat label="Total Activities" value={totalActivities.toLocaleString()} />
              <Stat label="Not Started" value={notStarted.toLocaleString()} />
              <Stat label="In Progress" value={inProgress.toLocaleString()} />
              <Stat label="Complete" value={complete.toLocaleString()} />
              <Stat label="Negative Float" value={negativeFloat.toLocaleString()} />
            </div>

            {/* Risk + Long Lead */}
            <SubHeading>Risk Summary</SubHeading>
            <div className="grid grid-cols-4 gap-3">
              <Stat label="Risks (Critical)" value={String(risksCritical)} accent="red" />
              <Stat label="Risks (High)" value={String(risksHigh)} accent="amber" />
              <Stat label="Risks (Medium)" value={String(risksMedium)} accent="slate" />
              <Stat label="Long Lead at Risk" value={`${longLeadAtRisk} / ${longLeadTotal}`} />
            </div>
          </section>

          {/* ============================================ CRITICAL PATH ============================================ */}
          {criticalDrivers.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="2" title="Critical Path Drivers" />
              <p className="text-sm text-slate-600 mb-4">
                Activities driving the project finish — total float ≤ 0 days. Showing top {criticalDrivers.length}
                {arr(a.criticalDrivers).length > criticalDrivers.length ? ` of ${arr(a.criticalDrivers).length}` : ''}.
              </p>
              <ActivityTable
                rows={criticalDrivers}
                columns={['code', 'name', 'float', 'earlyStart', 'earlyEnd']}
              />
            </section>
          )}

          {/* ============================================ LONGEST PATH ============================================ */}
          {longestPath.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="3" title="Longest Path" />
              <p className="text-sm text-slate-600 mb-4">
                Activities P6 flags via driving_path_flag = 'Y'. Showing top {longestPath.length}.
              </p>
              <ActivityTable
                rows={longestPath}
                columns={['code', 'name', 'float', 'earlyStart', 'earlyEnd']}
              />
            </section>
          )}

          {/* ============================================ MULTIPLE FLOAT PATHS (ControlLens) ============================================ */}
          {multiPathsResult && multiPathsResult.paths.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="4" title="Multiple Float Paths (ControlLens)" />
              <p className="text-sm text-slate-600 mb-2">
                ControlLens ranks the top driving chains of activities by total float — beyond just the single
                critical path that P6 shows. <strong>Path 1 is the critical path</strong> (zero or negative
                float). <strong>Paths 2–5 are near-critical</strong> — today's near-critical becomes tomorrow's
                critical after one slip. All paths run to the final completion milestone. This is the proper
                Multiple Float Paths method that federal claim analysts and PM teams use for delay analysis.
              </p>
              <p className="text-xs text-slate-500 italic mb-5">
                Float threshold: 5 days. {multiPathsResult.paths.length} paths shown.
                Drives to: {multiPathsResult.finalCompletionMilestone}.
              </p>

              {multiPathsResult.paths.map(path => {
                const tagBg = path.isCritical ? '#b91c1c' : path.isNearCritical ? '#d97706' : '#475569'
                const tagLabel = path.isCritical
                  ? `PATH ${path.pathNumber} · CRITICAL`
                  : path.isNearCritical
                    ? `PATH ${path.pathNumber} · NEAR-CRITICAL`
                    : `PATH ${path.pathNumber}`
                const floatLabel = path.floatDays < 0
                  ? `${path.floatDays} days float (behind)`
                  : path.floatDays === 0
                    ? '0 days float'
                    : `${path.floatDays} day${path.floatDays === 1 ? '' : 's'} float`
                return (
                  <div key={path.pathNumber} className="mb-5 border border-slate-200 rounded p-4 break-inside-avoid">
                    <div className="flex items-center gap-2 mb-2">
                      <span
                        className="text-xs font-bold uppercase tracking-wider px-2 py-1 rounded text-white"
                        style={{ backgroundColor: tagBg }}>
                        {tagLabel}
                      </span>
                      <span className="text-base font-semibold text-slate-900 flex-1">{path.pathName}</span>
                      <span className="text-xs text-slate-600">
                        {path.activities.length} activities · {floatLabel}
                      </span>
                    </div>
                    <p className="text-xs text-slate-600 leading-relaxed mb-3">{path.plainExplanation}</p>
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="border-b border-slate-200 text-[10px] font-bold text-slate-500 uppercase tracking-wider">
                          <th className="text-left py-1">Code</th>
                          <th className="text-left py-1">Activity</th>
                          <th className="text-right py-1">Start</th>
                          <th className="text-right py-1">Finish</th>
                          <th className="text-right py-1">Float</th>
                        </tr>
                      </thead>
                      <tbody>
                        {path.activities.slice(0, 30).map((t, i) => {
                          const fl = Math.round(parseFloat(t.total_float_hr_cnt || '0') / 8)
                          const flColor = fl < 0 ? '#dc2626' : fl === 0 ? '#b45309' : '#059669'
                          return (
                            <tr key={i} className="border-b border-slate-100">
                              <td className="py-1 font-mono font-semibold text-slate-800">{t.task_code}</td>
                              <td className="py-1 text-slate-700">{t.task_name}</td>
                              <td className="py-1 text-right text-slate-600">{(t.early_start_date || t.target_start_date || '').slice(0, 10)}</td>
                              <td className="py-1 text-right text-slate-600">{(t.early_end_date || t.target_end_date || '').slice(0, 10)}</td>
                              <td className="py-1 text-right font-bold" style={{ color: flColor }}>{fl}d</td>
                            </tr>
                          )
                        })}
                      </tbody>
                    </table>
                    {path.activities.length > 30 && (
                      <div className="text-[10px] text-slate-400 italic mt-2">
                        Showing first 30 of {path.activities.length} activities on this path.
                      </div>
                    )}
                  </div>
                )
              })}
            </section>
          )}

          {/* ============================================ OUT OF SEQUENCE ============================================ */}
          {outOfSequence.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="5" title="Construction Sequence Problems" />
              <p className="text-sm text-slate-600 mb-4">
                Activities started or finished out of logical order with their predecessor.
                Showing top {outOfSequence.length}{arr(a.outOfSequence).length > outOfSequence.length ? ` of ${arr(a.outOfSequence).length}` : ''}.
              </p>
              <table className="w-full">
                <thead>
                  <tr>
                    <th style={{ width: '15%' }}>Activity</th>
                    <th>Name</th>
                    <th style={{ width: '12%' }}>Category</th>
                    <th style={{ width: '10%' }}>Violations</th>
                    <th style={{ width: '15%' }}>First Predecessor</th>
                  </tr>
                </thead>
                <tbody>
                  {outOfSequence.map((o: any, i: number) => (
                    <tr key={i} className="print-avoid-break">
                      <td className="font-mono">{o.task?.task_code || '—'}</td>
                      <td>{trunc(o.task?.task_name, 60)}</td>
                      <td>{o.category || '—'}</td>
                      <td>{Array.isArray(o.violations) ? o.violations.length : 1}</td>
                      <td className="font-mono">{o.pred?.task_code || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </section>
          )}

          {/* ============================================ LONG LEAD ============================================ */}
          {longLeadItems.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="6" title="Long Lead Items" />
              <p className="text-sm text-slate-600 mb-4">
                Procurement activities ≥35 calendar days duration. Sorted by float ascending (most exposed first).
                {longLeadAtRisk > 0 && (
                  <span className="text-red-700 font-semibold"> {longLeadAtRisk} at risk (≤14 days float).</span>
                )}
              </p>
              <table className="w-full">
                <thead>
                  <tr>
                    <th style={{ width: '15%' }}>Activity</th>
                    <th>Name</th>
                    <th style={{ width: '10%' }}>Duration</th>
                    <th style={{ width: '10%' }}>Remaining</th>
                    <th style={{ width: '10%' }}>Float (d)</th>
                    <th style={{ width: '8%' }}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {longLeadItems.map((it: any, i: number) => (
                    <tr key={i} className="print-avoid-break">
                      <td className="font-mono">{it.task_code || '—'}</td>
                      <td>{trunc(it.task_name, 50)}</td>
                      <td>{it.durationDays}d</td>
                      <td>{it.remainingDays}d</td>
                      <td style={{ color: it.floatDays <= 14 ? '#dc2626' : '#1e293b', fontWeight: it.floatDays <= 14 ? 700 : 400 }}>
                        {it.floatDays}
                      </td>
                      <td>{statusLabel(it.status_code)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </section>
          )}

          {/* ============================================ SUBMITTALS ============================================ */}
          {submittals.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="7" title="Submittals" />
              <p className="text-sm text-slate-600 mb-4">
                Submit + Review/Approval activity pairs detected by activity name. {submittals.length} total.
              </p>
              <ActivityTable
                rows={submittals}
                columns={['code', 'name', 'float', 'earlyStart', 'earlyEnd', 'status']}
              />
            </section>
          )}

          {/* ============================================ MILESTONES ============================================ */}
          {milestones.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="8" title="Key Milestones" />
              <p className="text-sm text-slate-600 mb-4">
                Top upcoming milestones detected from the XER. {milestones.length} shown.
              </p>
              <ActivityTable
                rows={milestones}
                columns={['code', 'name', 'earlyStart', 'earlyEnd', 'status']}
              />
            </section>
          )}

          {/* ============================================ 2-WEEK LOOKAHEAD ============================================ */}
          {twoWeek.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="9" title="Two-Week Lookahead" />
              <p className="text-sm text-slate-600 mb-4">
                Activities scheduled to start or finish within 14 days of the data date ({fmtDate(dataDate)}).
                {twoWeek.length} activities.
              </p>
              <ActivityTable
                rows={twoWeek}
                columns={['code', 'name', 'earlyStart', 'earlyEnd', 'float', 'status']}
              />
            </section>
          )}

          {/* ============================================ NO TIES / LOGIC GAPS ============================================ */}
          {noTies.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="10" title="Activities with No Logic Ties" />
              <p className="text-sm text-slate-600 mb-4">
                Activities missing either a predecessor or successor — schedule quality issues that should be reviewed.
                Showing top {noTies.length}{arr(a.noTies).length > noTies.length ? ` of ${arr(a.noTies).length}` : ''}.
              </p>
              <ActivityTable
                rows={noTies}
                columns={['code', 'name', 'earlyStart', 'earlyEnd', 'status']}
              />
            </section>
          )}

          {/* ============================================ EVM ============================================ */}
          {evm && evm.totalBudget > 0 && Array.isArray(evm.months) && evm.months.length > 0 && (() => {
            const cum = evmCumulative(evm.totalBudget, evm.months, undefined)
            const currency = evm.currency || 'USD'
            return (
              <section className="print-page-break px-10 py-10">
                <SectionHeading num="11" title="Earned Value Management" />
                <p className="text-sm text-slate-600 mb-4">
                  Cumulative values across {evm.months.length} project month{evm.months.length === 1 ? '' : 's'}.
                  Total budget: {fmtDollars(evm.totalBudget, currency)}. Distribution: {evm.distributionMode}.
                </p>
                <SubHeading>Cumulative Values</SubHeading>
                <div className="grid grid-cols-4 gap-3 mb-5">
                  <Stat label="Total Budget (BAC)" value={fmtDollars(evm.totalBudget, currency)} />
                  <Stat label="Planned Value (PV)" value={fmtDollars(cum.pv, currency)} />
                  <Stat label="Earned Value (EV)" value={fmtDollars(cum.ev, currency)} />
                  <Stat label="Actual Cost (AC)" value={cum.hasAnyActualCost ? fmtDollars(cum.ac, currency) : '— not tracked'} />
                </div>
                <SubHeading>Performance Indices</SubHeading>
                <div className="grid grid-cols-4 gap-3 mb-5">
                  <Stat label="SPI (Schedule)" value={fmtEvmRatio(cum.spi)} accent={cum.spi !== null && cum.spi < 1 ? 'red' : 'slate'} />
                  <Stat label="CPI (Cost)" value={cum.hasAnyActualCost ? fmtEvmRatio(cum.cpi) : '— not tracked'} accent={cum.cpi !== null && cum.cpi < 1 ? 'red' : 'slate'} />
                  <Stat label="Schedule Variance" value={fmtDollars(cum.sv, currency)} accent={cum.sv < 0 ? 'red' : 'slate'} />
                  <Stat label="Cost Variance" value={cum.hasAnyActualCost && cum.cv !== null ? fmtDollars(cum.cv, currency) : '— not tracked'} accent={cum.cv !== null && cum.cv < 0 ? 'red' : 'slate'} />
                </div>
                <SubHeading>Monthly Breakdown</SubHeading>
                <table className="w-full">
                  <thead>
                    <tr>
                      <th style={{ width: '15%' }}>Month</th>
                      <th style={{ width: '13%' }}>Planned %</th>
                      <th style={{ width: '13%' }}>Earned %</th>
                      <th style={{ width: '20%' }}>Planned Value</th>
                      <th style={{ width: '20%' }}>Earned Value</th>
                      <th style={{ width: '19%' }}>Actual Cost</th>
                    </tr>
                  </thead>
                  <tbody>
                    {evm.months.map((m: any, i: number) => (
                      <tr key={i} className="print-avoid-break">
                        <td>{m.label}</td>
                        <td>{(m.plannedPct || 0).toFixed(1)}%</td>
                        <td>{(m.earnedPct || 0).toFixed(1)}%</td>
                        <td>{fmtDollars((m.plannedPct / 100) * evm.totalBudget, currency)}</td>
                        <td>{fmtDollars((m.earnedPct / 100) * evm.totalBudget, currency)}</td>
                        <td>{m.actualCost ? fmtDollars(m.actualCost, currency) : '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </section>
            )
          })()}

          {/* ============================================ APPENDIX — IN PROGRESS ============================================ */}
          {inProgressList.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="A1" title="Appendix — Activities In Progress" />
              <p className="text-sm text-slate-600 mb-4">
                Activities with status = In Progress. {inProgressList.length} total.
              </p>
              <ActivityTable
                rows={inProgressList}
                columns={['code', 'name', 'pct', 'float', 'earlyStart', 'earlyEnd']}
              />
            </section>
          )}

          {/* ============================================ APPENDIX — NOT STARTED ============================================ */}
          {notStartedList.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="A2" title="Appendix — Activities Not Started" />
              <p className="text-sm text-slate-600 mb-4">
                Activities with status = Not Started. Showing top {notStartedList.length}{arr(a.notStartedActivities).length > notStartedList.length ? ` of ${arr(a.notStartedActivities).length}` : ''}.
              </p>
              <ActivityTable
                rows={notStartedList}
                columns={['code', 'name', 'float', 'earlyStart', 'earlyEnd']}
              />
            </section>
          )}

          {/* ============================================ APPENDIX — FINISHED ============================================ */}
          {finishedList.length > 0 && (
            <section className="print-page-break px-10 py-10">
              <SectionHeading num="A3" title="Appendix — Recently Finished Activities" />
              <p className="text-sm text-slate-600 mb-4">
                Activities with status = Complete, sorted by actual finish date (most recent first).
                Showing top {finishedList.length}{arr(a.finishedActivities).length > finishedList.length ? ` of ${arr(a.finishedActivities).length}` : ''}.
              </p>
              <ActivityTable
                rows={finishedList}
                columns={['code', 'name', 'actStart', 'actEnd']}
              />
            </section>
          )}

          {/* ============================================ FOOTER PAGE ============================================ */}
          <section className="print-page-break px-12 py-16 text-center" style={{ minHeight: '6in' }}>
            <div className="flex items-center justify-center gap-3 mb-8">
              <ControlLensLogo />
              <div className="text-2xl font-extrabold">
                <span className="text-slate-800">Control</span><span className="text-blue-600">Lens</span>
              </div>
            </div>
            <div className="text-sm text-slate-600 max-w-md mx-auto leading-relaxed">
              This report was generated automatically from {project.name}'s Primavera P6 schedule on {generatedAt}.
              All metrics derived from {version.fileName}.
            </div>
            <div className="text-xs text-slate-400 mt-12">
              app.control-lens.com<br />
              Project controls intelligence built by PMs, for PMs.
            </div>
          </section>

        </div>
      </div>
    </>
  )
}

// =============================================================================
// Sub-components
// =============================================================================

function ControlLensLogo() {
  return (
    <div className="flex items-end gap-[3px] h-9">
      <div style={{ width: 7, height: 18, background: '#2563eb', borderRadius: 1 }} />
      <div style={{ width: 7, height: 28, background: '#dc2626', borderRadius: 1 }} />
      <div style={{ width: 7, height: 22, background: '#16a34a', borderRadius: 1 }} />
      <div style={{ width: 7, height: 34, background: '#475569', borderRadius: 1 }} />
    </div>
  )
}

function CoverRow({ label, value }: { label: string; value: string }) {
  return (
    <>
      <div className="text-xs uppercase tracking-wider text-slate-500 font-semibold">{label}</div>
      <div className="text-sm font-semibold text-slate-900">{value || '—'}</div>
    </>
  )
}

function SectionHeading({ num, title }: { num: string; title: string }) {
  return (
    <div className="flex items-baseline gap-3 mb-6 border-b border-slate-200 pb-3">
      <div className="text-xs uppercase tracking-[0.25em] text-blue-600 font-bold">Section {num}</div>
      <div className="text-2xl font-bold text-slate-900">{title}</div>
    </div>
  )
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return <div className="text-sm font-bold text-slate-700 uppercase tracking-wider mt-5 mb-3">{children}</div>
}

function Stat({ label, value, accent }: { label: string; value: string; accent?: 'red' | 'amber' | 'slate' }) {
  const color = accent === 'red' ? '#dc2626' : accent === 'amber' ? '#d97706' : '#0f172a'
  return (
    <div className="border border-slate-200 rounded-lg p-3 print-avoid-break">
      <div className="text-[9pt] uppercase tracking-wider text-slate-500 font-semibold">{label}</div>
      <div className="text-lg font-bold mt-1" style={{ color }}>{value}</div>
    </div>
  )
}

function ActivityTable({ rows, columns }: { rows: any[]; columns: string[] }) {
  const colDef: Record<string, { label: string; width?: string; render: (r: any) => string }> = {
    code: { label: 'Activity ID', width: '14%', render: r => r.task_code || r.code || '—' },
    name: { label: 'Activity Name', render: r => trunc(r.task_name || r.name || '—', 60) },
    float: { label: 'Float (hr)', width: '10%', render: r => r.total_float_hr_cnt || '0' },
    pct: { label: '% Complete', width: '10%', render: r => `${Math.round(parseFloat(r.phys_complete_pct || '0'))}%` },
    earlyStart: { label: 'Early Start', width: '13%', render: r => shortDate(r.early_start_date || r.target_start_date) },
    earlyEnd: { label: 'Early Finish', width: '13%', render: r => shortDate(r.early_end_date || r.target_end_date) },
    actStart: { label: 'Actual Start', width: '13%', render: r => shortDate(r.act_start_date) },
    actEnd: { label: 'Actual Finish', width: '13%', render: r => shortDate(r.act_end_date) },
    status: { label: 'Status', width: '10%', render: r => statusLabel(r.status_code) },
  }
  return (
    <table className="w-full">
      <thead>
        <tr>
          {columns.map(c => (
            <th key={c} style={colDef[c]?.width ? { width: colDef[c].width } : {}}>{colDef[c]?.label || c}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((r, i) => (
          <tr key={i} className="print-avoid-break">
            {columns.map(c => (
              <td key={c} className={c === 'code' ? 'font-mono' : ''}>
                {colDef[c]?.render(r) || '—'}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  )
}

// =============================================================================
// Helpers
// =============================================================================
function num(v: any, fallback: number): number {
  const n = typeof v === 'number' ? v : typeof v === 'string' ? parseFloat(v) : NaN
  return isFinite(n) ? n : fallback
}
function arr<T = any>(v: any): T[] {
  return Array.isArray(v) ? v : []
}
function fmtDate(d?: string): string {
  if (!d) return '—'
  try {
    const dt = new Date(d)
    if (isNaN(dt.getTime())) return String(d)
    return dt.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  } catch { return String(d) }
}
function shortDate(d?: string): string {
  if (!d) return '—'
  try {
    const dt = new Date(d.replace(' ', 'T'))
    if (isNaN(dt.getTime())) return '—'
    return dt.toLocaleDateString('en-US', { month: 'numeric', day: 'numeric', year: '2-digit' })
  } catch { return '—' }
}
function trunc(s: string | undefined, max: number): string {
  if (!s) return '—'
  return s.length > max ? s.slice(0, max - 1) + '…' : s
}
function statusLabel(code?: string): string {
  switch (code) {
    case 'TK_NotStart': return 'Not Started'
    case 'TK_Active': return 'In Progress'
    case 'TK_Complete': return 'Complete'
    default: return code || '—'
  }
}
function deriveCondition(score: number): string {
  if (score >= 80) return 'Stable'
  if (score >= 60) return 'Monitor Closely'
  if (score >= 40) return 'Attention Needed'
  return 'Recovery Required'
}
