// =============================================================================
// src/lib/construction/library.ts   (GENERATED from
// Control_Lens_Universal_Construction_Logic_Library_v1.xlsx — do not hand-edit;
// edit the workbook and re-run the generator. Rule prerequisites are normalized
// to canonical ActivityClass + Stage + Scope, not literal text.)
//
// Source of truth: the Excel workbook. This file is the engine-ready form.
// 19 rules · 19 classes · 17 milestones · 6 project modules
// =============================================================================
import type {
  ConstructionRule, ClassificationEntry, MilestoneDef, ProjectTypeModule,
} from './types'

export const CLASSIFICATION: ClassificationEntry[] = [
  {"activityClass": "MV_SWITCHGEAR", "discipline": "Electrical", "system": "MV Distribution", "keywords": ["mv switchgear", "medium voltage gear", "mv lineup", "medium voltage switchgear"], "stageHints": {"SET": ["install", "set"], "TEST": ["test"], "ENERGIZE": ["energize"]}},
  {"activityClass": "LV_SWITCHGEAR", "discipline": "Electrical", "system": "LV Distribution", "keywords": ["lv switchgear", "low voltage gear", "switchboard", "main distribution board", "mdb"], "stageHints": {"SET": ["install", "set"], "TEST": ["test"], "ENERGIZE": ["energize"]}},
  {"activityClass": "TRANSFORMER", "discipline": "Electrical", "system": "Transformer", "keywords": ["transformer", "xfmr", "unit substation"], "stageHints": {"DELIVER": ["deliver"], "SET": ["set"], "TERMINATE": ["terminate"], "TEST": ["test"], "ENERGIZE": ["energize"]}},
  {"activityClass": "GENERATOR", "discipline": "Electrical", "system": "Generator", "keywords": ["generator", "genset", "gen-set", "emergency generator"], "stageHints": {"DELIVER": ["deliver"], "SET": ["set"], "STARTUP": ["startup"], "LOAD_BANK": ["load bank"], "TEST": ["test"]}},
  {"activityClass": "ATS", "discipline": "Electrical", "system": "ATS", "keywords": ["ats", "automatic transfer switch", "transfer switch"], "stageHints": {"SET": ["install"], "TEST": ["test"], "TRANSFER": ["transfer"]}},
  {"activityClass": "UPS", "discipline": "Electrical", "system": "UPS", "keywords": ["ups", "uninterruptible power supply"], "stageHints": {"SET": ["install"], "CONNECT": ["battery"], "STARTUP": ["startup"], "TEST": ["load test"]}},
  {"activityClass": "EPMS", "discipline": "Electrical", "system": "EPMS", "keywords": ["epms", "electrical power monitoring", "power monitoring"], "stageHints": {"POINT_TO_POINT": ["point-to-point"], "TEST": ["alarm", "trend", "test"]}},
  {"activityClass": "CHILLER", "discipline": "Mechanical", "system": "Chillers", "keywords": ["chiller", "centrifugal chiller", "air cooled chiller", "water cooled chiller"], "stageHints": {"SET": ["install"], "STARTUP": ["startup"], "TEST": ["test"]}},
  {"activityClass": "CHW_SYSTEM", "discipline": "Mechanical", "system": "Chilled Water", "keywords": ["chilled water", "chw", "hydronic"], "stageHints": {"CONNECT": ["pipe"], "PRESSURE_TEST": ["pressure test"], "FLUSH_CLEAN": ["flush"], "TREAT": ["treat"], "FILL_CIRCULATE": ["fill", "circulate"], "FLOW": ["flow"]}},
  {"activityClass": "CRAH", "discipline": "Mechanical", "system": "CRAH/CRAC", "keywords": ["crah", "crac", "computer room air handler", "computer room air conditioner"], "stageHints": {"SET": ["install"], "STARTUP": ["startup"], "TEST": ["test"]}},
  {"activityClass": "AHU", "discipline": "Mechanical", "system": "AHU", "keywords": ["ahu", "air handling unit", "rooftop unit", "rtu", "make-up air", "mau"], "stageHints": {"SET": ["install"], "STARTUP": ["startup"], "TEST": ["test"]}},
  {"activityClass": "BMS", "discipline": "Mechanical", "system": "BMS", "keywords": ["bms", "building management system", "building automation", "bas"], "stageHints": {"POINT_TO_POINT": ["point-to-point"], "TEST": ["alarm", "sequence", "test"]}},
  {"activityClass": "TAB", "discipline": "Mechanical", "system": "TAB", "keywords": ["tab", "testing adjusting balancing", "air balance", "water balance"], "stageHints": {"TEST": ["test"]}},
  {"activityClass": "FOUNDATION", "discipline": "Structural", "system": "Foundations", "keywords": ["footing", "foundation", "pile cap", "grade beam", "caisson", "pier"], "stageHints": {"EXCAVATE": ["excavate"], "FORMWORK": ["form"], "REINFORCE": ["rebar"], "POUR": ["pour"], "CURE": ["cure"]}},
  {"activityClass": "STRUCTURAL_STEEL", "discipline": "Structural", "system": "Structural Steel", "keywords": ["structural steel", "erect steel", "steel erection", "column", "beam", "joist"], "stageHints": {"ERECT": ["erect"], "ANCHOR": ["bolt"], "CONNECT": ["weld"], "INSPECT": ["inspect"]}},
  {"activityClass": "PRECAST", "discipline": "Structural", "system": "Precast", "keywords": ["precast", "double t", "double tee", "hollowcore"], "stageHints": {"ERECT": ["erect"], "SET": ["install"]}},
  {"activityClass": "EXTERIOR_ENVELOPE", "discipline": "Architectural", "system": "Envelope", "keywords": ["weather tight", "watertight", "dry-in", "curtainwall", "storefront", "exterior wall", "roofing"], "stageHints": {"SET": ["install"], "TEST": ["test"], "MILESTONE": ["milestone"]}},
  {"activityClass": "COMMISSIONING", "discipline": "Commissioning", "system": "General", "keywords": ["commission", "startup", "functional test", "fpt", "ist", "integrated systems test"], "stageHints": {"STARTUP": ["startup"], "TEST": ["test"], "ACCEPT": ["accept"]}},
  {"activityClass": "PUNCH", "discipline": "QAQC", "system": "Punch List", "keywords": ["punch", "deficiency", "prefinal", "final inspection"], "stageHints": {"INSPECT": ["inspect"], "DEFICIENCY": ["correct"], "CLOSE": ["close"]}}
] as ClassificationEntry[]

export const RULES: ConstructionRule[] = [
  {"id": "R-001", "trigger": {"activityClass": "STRUCTURAL_STEEL", "stage": "ERECT"}, "prerequisites": [{"activityClass": ["FOOTING", "FOUNDATION", "FOUNDATION_WALL", "PILE_CAP", "GRADE_BEAM", "MAT_FOUNDATION", "EQUIPMENT_FOUNDATION", "PRECAST"], "stage": "COMPLETE", "scope": ["SAME_BUILDING", "SAME_AREA"], "mode": "ANY", "optional": false, "label": "Foundation Complete"}], "recommendedChain": [{"order": 1, "label": "Foundation Complete"}, {"order": 2, "label": "Anchor Bolts Verified"}, {"order": 3, "label": "Steel Erection"}], "targetMilestone": "STRUCTURE_COMPLETE", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "Structural steel erection lacks a foundation-completion prerequisite."},
  {"id": "R-002", "trigger": {"activityClass": "SENSITIVE_ELEC_EQUIP", "stage": "SET"}, "prerequisites": [{"activityClass": ["EXTERIOR_ENVELOPE", "ROOFING", "GLAZING"], "stage": "COMPLETE", "scope": ["SAME_BUILDING"], "mode": "ANY", "optional": true, "label": "Building Dry-In"}], "recommendedChain": [{"order": 1, "label": "Building Dry-In"}, {"order": 2, "label": "Room/Pad Ready"}, {"order": 3, "label": "Equipment Set"}], "targetMilestone": "PERMANENT_POWER", "ruleType": "REVIEW", "severity": 2, "applicability": ["ALL"], "findingText": "Sensitive equipment is set before building dry-in; verify approved protection and manufacturer requirements."},
  {"id": "R-003", "trigger": {"activityClass": "MV_SWITCHGEAR", "stage": "ENERGIZE"}, "prerequisites": [{"activityClass": "MV_CABLE", "stage": "TEST", "scope": ["SAME_SYSTEM", "SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "MV Cable Testing"}, {"activityClass": "MV_CABLE", "stage": "TEST", "scope": ["SAME_SYSTEM"], "mode": "ALL", "optional": false, "label": "Phasing"}, {"activityClass": "MV_SWITCHGEAR", "stage": "TEST", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Relay/Breaker Testing"}], "recommendedChain": [{"order": 1, "label": "Terminate"}, {"order": 2, "label": "Cable Test"}, {"order": 3, "label": "Phasing"}, {"order": 4, "label": "Protection Test"}, {"order": 5, "label": "Energize"}], "targetMilestone": "PERMANENT_POWER", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "MV energization appears to precede required cable/protection testing."},
  {"id": "R-004", "trigger": {"activityClass": "TRANSFORMER", "stage": "ENERGIZE"}, "prerequisites": [{"activityClass": "TRANSFORMER", "stage": "TERMINATE", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Primary/Secondary Connections"}, {"activityClass": "TRANSFORMER", "stage": "GROUND", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Grounding"}, {"activityClass": "TRANSFORMER", "stage": "TEST", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Transformer Testing"}], "recommendedChain": [{"order": 1, "label": "Set"}, {"order": 2, "label": "Ground"}, {"order": 3, "label": "Terminate"}, {"order": 4, "label": "Test"}, {"order": 5, "label": "Energize"}], "targetMilestone": "PERMANENT_POWER", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "Transformer energization lacks required testing/connection prerequisites."},
  {"id": "R-005", "trigger": {"activityClass": "UPS", "stage": "FUNCTIONAL_TEST"}, "prerequisites": [{"activityClass": "BATTERY", "stage": "CONNECT", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Battery System Connected"}, {"activityClass": "UPS", "stage": "STARTUP", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "UPS Startup"}], "recommendedChain": [{"order": 1, "label": "Set"}, {"order": 2, "label": "Connect Batteries"}, {"order": 3, "label": "Startup"}, {"order": 4, "label": "Functional/Load Test"}], "targetMilestone": "ELECTRICAL_FPT", "ruleType": "HARD", "severity": 5, "applicability": ["MISSION_CRITICAL"], "findingText": "UPS functional testing appears to precede battery-system completion/startup."},
  {"id": "R-006", "trigger": {"activityClass": "GENERATOR", "stage": "LOAD_BANK"}, "prerequisites": [{"activityClass": ["FUEL_GAS", "GENERATOR"], "stage": "CONNECT", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Fuel/Gas Connected"}, {"activityClass": "GENERATOR", "stage": "STARTUP", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Generator Startup"}], "recommendedChain": [{"order": 1, "label": "Set"}, {"order": 2, "label": "Fuel/Gas"}, {"order": 3, "label": "Electrical/Controls"}, {"order": 4, "label": "Startup"}, {"order": 5, "label": "Load Bank"}], "targetMilestone": "ELECTRICAL_FPT", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "Generator load-bank testing lacks source/startup prerequisites."},
  {"id": "R-007", "trigger": {"activityClass": "ATS", "stage": "FUNCTIONAL_TEST"}, "prerequisites": [{"activityClass": ["NORMAL_SOURCE", "ATS"], "stage": "CONNECT", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Normal Source"}, {"activityClass": ["EMERGENCY_SOURCE", "GENERATOR"], "stage": "CONNECT", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Emergency Source"}, {"activityClass": "ATS", "stage": "CONTROLS", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "ATS Controls"}], "recommendedChain": [{"order": 1, "label": "Connect Both Sources"}, {"order": 2, "label": "Controls"}, {"order": 3, "label": "ATS Functional Test"}], "targetMilestone": "ELECTRICAL_FPT", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "ATS functional test lacks one or more required source/control prerequisites."},
  {"id": "R-008", "trigger": {"activityClass": "CRAH", "stage": "FUNCTIONAL_TEST"}, "prerequisites": [{"activityClass": ["CHW_SYSTEM", "CHILLER"], "stage": "FLOW", "scope": ["SAME_SYSTEM", "SAME_BUILDING"], "mode": "ALL", "optional": false, "label": "Chilled Water Flow"}, {"activityClass": "CRAH", "stage": "STARTUP", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "Startup"}, {"activityClass": "BMS", "stage": "POINT_TO_POINT", "scope": ["SAME_AREA", "SAME_BUILDING"], "mode": "ALL", "optional": false, "label": "BMS Point-to-Point"}], "recommendedChain": [{"order": 1, "label": "CHW Flow"}, {"order": 2, "label": "CRAH Startup"}, {"order": 3, "label": "BMS P2P"}, {"order": 4, "label": "TAB"}, {"order": 5, "label": "Functional Test"}], "targetMilestone": "MECHANICAL_FPT", "ruleType": "HARD", "severity": 5, "applicability": ["MISSION_CRITICAL"], "findingText": "CRAH/CRAC functional testing appears before chilled-water/controls readiness."},
  {"id": "R-009", "trigger": {"activityClass": "CHILLER", "stage": "STARTUP"}, "prerequisites": [{"activityClass": ["CHW_PIPE", "CHW_SYSTEM"], "stage": "PRESSURE_TEST", "scope": ["SAME_SYSTEM"], "mode": "ALL", "optional": false, "label": "CHW Pressure Test"}, {"activityClass": "CHW_SYSTEM", "stage": "FLUSH_CLEAN", "scope": ["SAME_SYSTEM"], "mode": "ALL", "optional": false, "label": "Flush/Clean"}, {"activityClass": "CHW_SYSTEM", "stage": "TREAT", "scope": ["SAME_SYSTEM"], "mode": "ALL", "optional": false, "label": "Treatment"}, {"activityClass": "CHW_SYSTEM", "stage": "FILL_CIRCULATE", "scope": ["SAME_SYSTEM"], "mode": "ALL", "optional": false, "label": "Final Fill/Circulation"}], "recommendedChain": [{"order": 1, "label": "CHW Complete"}, {"order": 2, "label": "Pressure Test"}, {"order": 3, "label": "Flush/Clean"}, {"order": 4, "label": "Treat"}, {"order": 5, "label": "Final Fill/Circulate"}, {"order": 6, "label": "Startup"}], "targetMilestone": "MECHANICAL_FPT", "ruleType": "HARD", "severity": 5, "applicability": ["MISSION_CRITICAL"], "findingText": "Chiller startup appears before chilled-water cleaning/treatment/flow readiness."},
  {"id": "R-010", "trigger": {"activityClass": "AHU", "stage": "TAB"}, "prerequisites": [{"activityClass": "AHU", "stage": "STARTUP", "scope": ["SAME_EQUIPMENT_TRAIN"], "mode": "ALL", "optional": false, "label": "AHU Startup"}, {"activityClass": ["BMS", "AHU"], "stage": "CONTROLS", "scope": ["SAME_AREA", "SAME_BUILDING"], "mode": "ALL", "optional": false, "label": "Controls Operational"}], "recommendedChain": [{"order": 1, "label": "AHU Install"}, {"order": 2, "label": "Startup"}, {"order": 3, "label": "BMS P2P"}, {"order": 4, "label": "TAB"}], "targetMilestone": "MECHANICAL_FPT", "ruleType": "HARD", "severity": 4, "applicability": ["ALL"], "findingText": "TAB appears before air-handling system startup/controls readiness."},
  {"id": "R-011", "trigger": {"activityClass": "BMS", "stage": "FUNCTIONAL_TEST"}, "prerequisites": [{"activityClass": "BMS", "stage": "POINT_TO_POINT", "scope": ["SAME_SYSTEM", "SAME_BUILDING"], "mode": "ALL", "optional": false, "label": "Point-to-Point"}, {"activityClass": "BMS", "stage": "TEST", "scope": ["SAME_SYSTEM", "SAME_BUILDING"], "mode": "ALL", "optional": false, "label": "Alarm/Sequence Verification"}], "recommendedChain": [{"order": 1, "label": "BMS Network"}, {"order": 2, "label": "P2P"}, {"order": 3, "label": "Alarms/Sequences"}, {"order": 4, "label": "Functional Test"}], "targetMilestone": "READY_FOR_IST", "ruleType": "HARD", "severity": 4, "applicability": ["ALL"], "findingText": "BMS functional testing lacks point-to-point/alarm prerequisites."},
  {"id": "R-012", "trigger": {"activityClass": "EPMS", "stage": "FUNCTIONAL_TEST"}, "prerequisites": [{"activityClass": "EPMS", "stage": "POINT_TO_POINT", "scope": ["SAME_SYSTEM"], "mode": "ALL", "optional": false, "label": "Point-to-Point"}, {"activityClass": "EPMS", "stage": "TEST", "scope": ["SAME_SYSTEM"], "mode": "ALL", "optional": false, "label": "Alarm/Trending Verification"}], "recommendedChain": [{"order": 1, "label": "EPMS P2P"}, {"order": 2, "label": "Alarm/Trend Verify"}, {"order": 3, "label": "Electrical FPT"}, {"order": 4, "label": "IST"}], "targetMilestone": "READY_FOR_IST", "ruleType": "EXPECTED", "severity": 4, "applicability": ["MISSION_CRITICAL"], "findingText": "IST path appears unsupported by complete EPMS verification."},
  {"id": "R-013", "trigger": {"activityClass": "IST", "stage": "IST"}, "prerequisites": [{"activityClass": "ELECTRICAL_FPT", "stage": "FUNCTIONAL_TEST", "scope": ["PROJECT_WIDE"], "mode": "ALL", "optional": false, "label": "Electrical FPT"}, {"activityClass": "MECHANICAL_FPT", "stage": "FUNCTIONAL_TEST", "scope": ["PROJECT_WIDE"], "mode": "ALL", "optional": false, "label": "Mechanical FPT"}, {"activityClass": ["CONTROLS_FPT", "BMS"], "stage": "FUNCTIONAL_TEST", "scope": ["PROJECT_WIDE"], "mode": "ALL", "optional": false, "label": "Controls FPT"}, {"activityClass": ["LIFE_SAFETY_FPT", "FIRE_ALARM", "SPRINKLER"], "stage": "TEST", "scope": ["PROJECT_WIDE"], "mode": "ALL", "optional": true, "label": "Required Life Safety FPT"}], "recommendedChain": [{"order": 1, "label": "Subsystem FPTs"}, {"order": 2, "label": "IST Readiness"}, {"order": 3, "label": "IST"}], "targetMilestone": "IST_COMPLETE", "ruleType": "HARD", "severity": 5, "applicability": ["MISSION_CRITICAL"], "findingText": "Integrated Systems Testing is not fully predecessor-driven by required subsystem functional tests."},
  {"id": "R-014", "trigger": {"activityClass": "SLAB_ON_GRADE", "stage": "POUR"}, "prerequisites": [{"activityClass": "MEP_ROUGHIN", "stage": "ROUGH_IN", "scope": ["SAME_AREA"], "mode": "ALL", "optional": false, "label": "Under-Slab MEP"}, {"activityClass": "MEP_ROUGHIN", "stage": "GROUND", "scope": ["SAME_AREA"], "mode": "ANY", "optional": true, "label": "Grounding"}, {"activityClass": "INSPECTION", "stage": "INSPECT", "scope": ["SAME_AREA"], "mode": "ALL", "optional": false, "label": "Pre-Pour Inspection"}], "recommendedChain": [{"order": 1, "label": "Underslab MEP/Grounding"}, {"order": 2, "label": "Vapor Barrier/Rebar"}, {"order": 3, "label": "Inspection"}, {"order": 4, "label": "Pour"}], "targetMilestone": "FOUNDATIONS_COMPLETE", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "Slab placement lacks underground/pre-pour prerequisites."},
  {"id": "R-015", "trigger": {"activityClass": "CABLE_PULL", "stage": "SET"}, "prerequisites": [{"activityClass": "DUCTBANK", "stage": "COMPLETE", "scope": ["SAME_SYSTEM", "SAME_AREA"], "mode": "ALL", "optional": false, "label": "Duct Bank/Conduit Complete"}, {"activityClass": "DUCTBANK", "stage": "SET", "scope": ["SAME_SYSTEM", "SAME_AREA"], "mode": "ANY", "optional": true, "label": "Manholes/Pull Points Ready"}], "recommendedChain": [{"order": 1, "label": "Duct Bank"}, {"order": 2, "label": "Manholes/Pull Boxes"}, {"order": 3, "label": "Cable Pull"}], "targetMilestone": "PERMANENT_POWER", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "Cable pulling appears before pathway/pull-point readiness."},
  {"id": "R-016", "trigger": {"activityClass": "INTERIOR_DRYWALL", "stage": "CLOSE"}, "prerequisites": [{"activityClass": "MEP_ROUGHIN", "stage": "ROUGH_IN", "scope": ["SAME_AREA"], "mode": "ALL", "optional": false, "label": "In-Wall MEP"}, {"activityClass": "LV_ROUGHIN", "stage": "ROUGH_IN", "scope": ["SAME_AREA"], "mode": "ALL", "optional": true, "label": "Low Voltage Rough-In"}, {"activityClass": "INSPECTION", "stage": "INSPECT", "scope": ["SAME_AREA"], "mode": "ALL", "optional": false, "label": "Inspection"}], "recommendedChain": [{"order": 1, "label": "Framing"}, {"order": 2, "label": "MEP/LV Rough-In"}, {"order": 3, "label": "Inspection"}, {"order": 4, "label": "Drywall Close"}], "targetMilestone": "ARCHITECTURAL_COMPLETE", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "Wall closure appears before in-wall rough-in/inspection completion."},
  {"id": "R-017", "trigger": {"activityClass": "CEILING", "stage": "CLOSE"}, "prerequisites": [{"activityClass": "MEP_ROUGHIN", "stage": "ROUGH_IN", "scope": ["SAME_AREA"], "mode": "ALL", "optional": false, "label": "Above-Ceiling MEP"}, {"activityClass": "INSPECTION", "stage": "INSPECT", "scope": ["SAME_AREA"], "mode": "ALL", "optional": false, "label": "Inspection"}], "recommendedChain": [{"order": 1, "label": "Grid/Rough-In"}, {"order": 2, "label": "Above-Ceiling Inspection"}, {"order": 3, "label": "Ceiling Closure"}], "targetMilestone": "ARCHITECTURAL_COMPLETE", "ruleType": "HARD", "severity": 5, "applicability": ["ALL"], "findingText": "Ceiling closure appears before above-ceiling MEP inspection."},
  {"id": "R-018", "trigger": {"activityClass": "FIRE_MARSHAL", "stage": "INSPECT"}, "prerequisites": [{"activityClass": "SPRINKLER", "stage": "TEST", "scope": ["SAME_BUILDING"], "mode": "ALL", "optional": false, "label": "Sprinkler Test"}, {"activityClass": "FIRE_ALARM", "stage": "TEST", "scope": ["SAME_BUILDING"], "mode": "ALL", "optional": false, "label": "Fire Alarm Test"}, {"activityClass": "SMOKE_CONTROL", "stage": "TEST", "scope": ["SAME_BUILDING"], "mode": "ANY", "optional": true, "label": "Smoke Control Test"}], "recommendedChain": [{"order": 1, "label": "System Tests"}, {"order": 2, "label": "AHJ/Fire Marshal Inspection"}, {"order": 3, "label": "Life Safety Accepted"}], "targetMilestone": "LIFE_SAFETY_ACCEPTED", "ruleType": "EXPECTED", "severity": 4, "applicability": ["ALL"], "findingText": "Life-safety acceptance path lacks required system tests."},
  {"id": "R-019", "trigger": {"activityClass": "CO", "stage": "MILESTONE"}, "prerequisites": [{"activityClass": "CO", "stage": "ACCEPT", "scope": ["PROJECT_WIDE"], "mode": "ALL", "optional": false, "label": "CO/Use Permit"}, {"activityClass": "COMMISSIONING", "stage": "ACCEPT", "scope": ["PROJECT_WIDE"], "mode": "ALL", "optional": false, "label": "Commissioning Acceptance"}, {"activityClass": "PUNCH", "stage": "CLOSE", "scope": ["PROJECT_WIDE"], "mode": "ALL", "optional": true, "label": "Punch Threshold"}, {"activityClass": "TRAINING_OM", "stage": "ACCEPT", "scope": ["PROJECT_WIDE"], "mode": "ALL", "optional": true, "label": "Training/O&M per contract"}], "recommendedChain": [{"order": 1, "label": "Occupancy/Commissioning/Punch/Docs"}, {"order": 2, "label": "Substantial Completion"}], "targetMilestone": "SUBSTANTIAL_COMPLETION", "ruleType": "EXPECTED", "severity": 4, "applicability": ["ALL"], "findingText": "Substantial Completion is not fully supported by typical contractual closeout prerequisites."}
] as ConstructionRule[]

export const MILESTONES: MilestoneDef[] = [
  {"id": "MS-001", "milestoneClass": "Baseline Approved", "name": "Baseline Approved", "aliases": ["baseline approved"], "drivingDisciplines": ["Project Controls"], "backwardFocus": "NTP, design basis, schedule development", "forwardFocus": "All execution work", "applicability": "All"},
  {"id": "MS-002", "milestoneClass": "FOUNDATIONS_COMPLETE", "name": "Foundations Complete", "aliases": ["foundations complete"], "drivingDisciplines": ["Civil/Structural"], "backwardFocus": "Excavation, subgrade, footings, walls, slab", "forwardFocus": "Structure", "applicability": "All"},
  {"id": "MS-003", "milestoneClass": "STRUCTURE_COMPLETE", "name": "Structure Complete", "aliases": ["structure complete"], "drivingDisciplines": ["Structural"], "backwardFocus": "Foundations, steel/concrete/precast", "forwardFocus": "Envelope, MEP rough-in", "applicability": "All"},
  {"id": "MS-004", "milestoneClass": "Building Weather-Tight", "name": "Building Weather-Tight", "aliases": ["building weather-tight"], "drivingDisciplines": ["Envelope"], "backwardFocus": "Structure, roofing, walls, windows, doors", "forwardFocus": "Sensitive equipment, interiors", "applicability": "All"},
  {"id": "MS-005", "milestoneClass": "Building Dry-In", "name": "Building Dry-In", "aliases": ["building dry-in"], "drivingDisciplines": ["Envelope"], "backwardFocus": "Weather-tight and environmental protection", "forwardFocus": "Interior finishes, sensitive equipment", "applicability": "All"},
  {"id": "MS-006", "milestoneClass": "Utility Service Available", "name": "Utility Service Available", "aliases": ["utility service available"], "drivingDisciplines": ["Electrical/Utility"], "backwardFocus": "Utility design, agreements, construction", "forwardFocus": "Permanent Power", "applicability": "All"},
  {"id": "MS-007", "milestoneClass": "Permanent Power Available", "name": "Permanent Power Available", "aliases": ["permanent power available"], "drivingDisciplines": ["Electrical"], "backwardFocus": "Utility + MV + transformer + LV readiness", "forwardFocus": "Startup, controls, commissioning", "applicability": "All"},
  {"id": "MS-008", "milestoneClass": "Chilled Water Flow Available", "name": "Chilled Water Flow Available", "aliases": ["chilled water flow available"], "drivingDisciplines": ["Mechanical"], "backwardFocus": "Chillers, pumps, CHW piping, test/flush/treat/fill", "forwardFocus": "Cooling startup, TAB, FPT", "applicability": "Mission Critical/Hospital/Large HVAC"},
  {"id": "MS-009", "milestoneClass": "Electrical FPT Complete", "name": "Electrical FPT Complete", "aliases": ["electrical fpt complete"], "drivingDisciplines": ["Electrical/Commissioning"], "backwardFocus": "Switchgear, generator, ATS, UPS, EPMS", "forwardFocus": "IST readiness", "applicability": "All with commissioning"},
  {"id": "MS-010", "milestoneClass": "Mechanical FPT Complete", "name": "Mechanical FPT Complete", "aliases": ["mechanical fpt complete"], "drivingDisciplines": ["Mechanical/Commissioning"], "backwardFocus": "HVAC startup, controls, TAB", "forwardFocus": "IST readiness", "applicability": "All with commissioning"},
  {"id": "MS-011", "milestoneClass": "LIFE_SAFETY_ACCEPTED", "name": "Life Safety Accepted", "aliases": ["life safety accepted"], "drivingDisciplines": ["Fire Protection"], "backwardFocus": "Sprinkler, fire alarm, smoke control", "forwardFocus": "Occupancy/Substantial Completion", "applicability": "All"},
  {"id": "MS-012", "milestoneClass": "READY_FOR_IST", "name": "Ready for IST", "aliases": ["ready for ist"], "drivingDisciplines": ["Commissioning"], "backwardFocus": "All required subsystem FPTs", "forwardFocus": "IST", "applicability": "Mission Critical / complex systems"},
  {"id": "MS-013", "milestoneClass": "IST_COMPLETE", "name": "IST Complete", "aliases": ["ist complete"], "drivingDisciplines": ["Commissioning"], "backwardFocus": "IST readiness, approved procedure", "forwardFocus": "Corrections, acceptance", "applicability": "Mission Critical / complex systems"},
  {"id": "MS-014", "milestoneClass": "Commissioning Accepted", "name": "Commissioning Accepted", "aliases": ["commissioning accepted"], "drivingDisciplines": ["Commissioning"], "backwardFocus": "FPT/IST deficiencies closed", "forwardFocus": "Substantial Completion", "applicability": "All with commissioning"},
  {"id": "MS-015", "milestoneClass": "Certificate of Occupancy", "name": "Certificate of Occupancy", "aliases": ["certificate of occupancy"], "drivingDisciplines": ["Closeout/AHJ"], "backwardFocus": "Life safety, inspections, permits", "forwardFocus": "Substantial Completion/occupancy", "applicability": "All"},
  {"id": "MS-016", "milestoneClass": "SUBSTANTIAL_COMPLETION", "name": "Substantial Completion", "aliases": ["substantial completion"], "drivingDisciplines": ["Closeout"], "backwardFocus": "Contract-defined prerequisites", "forwardFocus": "Final Completion", "applicability": "All"},
  {"id": "MS-017", "milestoneClass": "Final Completion", "name": "Final Completion", "aliases": ["final completion"], "drivingDisciplines": ["Closeout"], "backwardFocus": "Punch, docs, final acceptance", "forwardFocus": "Warranty/contract close", "applicability": "All"}
] as MilestoneDef[]

export const PROJECT_MODULES: ProjectTypeModule[] = [
  {"projectType": "Data Center", "additionalSystems": "MV/LV distribution; UPS; batteries; generator; ATS; EPMS; BMS; chilled water; CRAH/CRAC; rack power; load banks; IST", "extraMilestones": "Permanent Power; Chilled Water Flow; Electrical FPT; Mechanical FPT; Ready for IST; IST Complete; Ready for Service", "notes": "Use high-rigor commissioning logic."},
  {"projectType": "Hospital / Healthcare", "additionalSystems": "Emergency power; ATS; medical gas; nurse call; fire/life safety; HVAC pressure relationships; BMS; infection control", "extraMilestones": "Life Safety Accepted; Medical Gas Certified; Clinical Systems Accepted; CO; Substantial Completion", "notes": "Allow phased occupancy/department turnover only if contract permits."},
  {"projectType": "Fire Station / EMS", "additionalSystems": "Emergency generator; ATS; vehicle exhaust capture; apparatus bay systems; fire alarm/sprinkler; domestic/fire water", "extraMilestones": "Station Emergency Power Accepted; Vehicle Exhaust Functional; CO; Substantial Completion", "notes": "Apparatus bay operational readiness is important."},
  {"projectType": "School", "additionalSystems": "Classrooms; IT/AV; fire/life safety; kitchen; gym; security/access control", "extraMilestones": "Life Safety Accepted; CO; Owner Training; Substantial Completion", "notes": "Often summer/academic-calendar milestone sensitive."},
  {"projectType": "Administrative Building", "additionalSystems": "Standard HVAC; electrical; fire/life safety; security; telecom; interiors", "extraMilestones": "Permanent Power; Life Safety Accepted; CO; Substantial Completion", "notes": "Core commercial/institutional sequence."},
  {"projectType": "Renovation / Occupied Facility", "additionalSystems": "Phasing; temporary utilities; infection/dust control if applicable; swing space; shutdowns", "extraMilestones": "Phase Turnover; Temporary Service Cutovers; Final Turnover", "notes": "Rules must be phase/location aware."}
] as ProjectTypeModule[]

export const LIBRARY_STATS = { rules: 19, classes: 19, milestones: 17, modules: 6 }
