import { NextRequest, NextResponse } from 'next/server'
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, ShadingType, PageBreak
} from 'docx'
import type { TrendAnalysisResult } from '@/lib/trendAnalyzer'

const COLOR_PRIMARY = '1e3a8a'
const COLOR_RED = 'b91c1c'
const COLOR_AMBER = 'b45309'
const COLOR_GREEN = '15803d'
const COLOR_GREY = '475569'

function shortDate(d: string): string {
  try { return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }) }
  catch { return d.slice(0, 10) }
}

function recColor(type: string): string {
  if (type === 'HEALTHY') return COLOR_GREEN
  if (type === 'SCHEDULE_UPDATE_REQUIRED') return COLOR_PRIMARY
  if (type === 'REBASELINE_RECOMMENDED') return COLOR_AMBER
  return COLOR_RED
}

function heading(text: string, level: any = HeadingLevel.HEADING_1): Paragraph {
  return new Paragraph({
    heading: level,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, color: COLOR_PRIMARY, bold: true })],
  })
}

function para(text: string, opts: { bold?: boolean; color?: string; size?: number; italics?: boolean } = {}): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({
      text,
      bold: opts.bold,
      color: opts.color,
      size: opts.size,
      italics: opts.italics,
    })],
  })
}

function bullet(text: string): Paragraph {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text })],
  })
}

function tableCell(text: string, opts: { bold?: boolean; color?: string; bg?: string } = {}): TableCell {
  return new TableCell({
    shading: opts.bg ? { type: ShadingType.CLEAR, fill: opts.bg, color: 'auto' } : undefined,
    children: [new Paragraph({
      children: [new TextRun({ text, bold: opts.bold, color: opts.color, size: 18 })],
    })],
  })
}

export async function POST(req: NextRequest) {
  try {
    const { trend } = await req.json() as { trend: TrendAnalysisResult }

    if (!trend) {
      return NextResponse.json({ error: 'No trend data provided' }, { status: 400 })
    }

    const children: (Paragraph | Table)[] = []

    // COVER PAGE
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 2400, after: 240 },
      children: [new TextRun({ text: 'TREND ANALYSIS REPORT', size: 48, bold: true, color: COLOR_PRIMARY })],
    }))
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 120 },
      children: [new TextRun({ text: trend.projectName, size: 32, bold: true })],
    }))
    if (trend.projectId) {
      children.push(new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 240 },
        children: [new TextRun({ text: `Project ID: ${trend.projectId}`, size: 22, color: COLOR_GREY })],
      }))
    }
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 120 },
      children: [new TextRun({ text: `Analysis of ${trend.versionsAnalyzed} schedule versions`, size: 22, color: COLOR_GREY })],
    }))
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
      children: [new TextRun({ text: `${shortDate(trend.firstUpload)} — ${shortDate(trend.latestUpload)}  (${trend.timeSpanDays} days)`, size: 20, color: COLOR_GREY })],
    }))
    children.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [new TextRun({ text: `Generated by NobelPM · ${shortDate(new Date().toISOString())}`, size: 18, color: COLOR_GREY, italics: true })],
    }))
    children.push(new Paragraph({ children: [new PageBreak()] }))

    // NOBELPM RECOMMENDATION
    children.push(heading('NobelPM Recommendation'))
    children.push(new Paragraph({
      spacing: { after: 240 },
      children: [new TextRun({
        text: trend.recommendation.title,
        size: 32, bold: true, color: recColor(trend.recommendation.type),
      })],
    }))
    children.push(para(trend.recommendation.summary, { size: 22 }))

    children.push(heading('Reasoning', HeadingLevel.HEADING_2))
    trend.recommendation.reasoning.forEach(r => children.push(bullet(r)))

    children.push(heading('Recommended Actions', HeadingLevel.HEADING_2))
    trend.recommendation.actions.forEach(a => children.push(bullet(a)))

    children.push(new Paragraph({ children: [new PageBreak()] }))

    // TREND SUMMARY
    children.push(heading('Trend Summary'))

    const trendLabel = trend.summary.trendDirection === 'IMPROVING' ? 'Improving' :
      trend.summary.trendDirection === 'STABLE' ? 'Stable' :
      trend.summary.trendDirection === 'DETERIORATING' ? 'Deteriorating' : 'Severely Deteriorating'

    children.push(para(`Overall trend direction: ${trendLabel}`, { bold: true }))
    children.push(bullet(`Delay change: ${trend.summary.overallDelayChange > 0 ? '+' : ''}${trend.summary.overallDelayChange} days`))
    children.push(bullet(`Negative float change: ${trend.summary.overallNegFloatChange > 0 ? '+' : ''}${trend.summary.overallNegFloatChange} activities`))
    children.push(bullet(`Health score change: ${trend.summary.overallHealthChange > 0 ? '+' : ''}${trend.summary.overallHealthChange} points`))
    children.push(bullet(`Completion change: ${trend.summary.overallCompletionChange > 0 ? '+' : ''}${trend.summary.overallCompletionChange}%`))
    children.push(bullet(`Average monthly delay growth: ${trend.summary.averageMonthlyDelayGrowth > 0 ? '+' : ''}${trend.summary.averageMonthlyDelayGrowth} days/month`))

    // VERSION DATA TABLE
    children.push(heading('Version-by-Version Data', HeadingLevel.HEADING_2))

    const dataRows: TableRow[] = []
    dataRows.push(new TableRow({
      tableHeader: true,
      children: [
        tableCell('Ver', { bold: true, bg: 'e2e8f0' }),
        tableCell('Data Date', { bold: true, bg: 'e2e8f0' }),
        tableCell('Uploaded', { bold: true, bg: 'e2e8f0' }),
        tableCell('Activities', { bold: true, bg: 'e2e8f0' }),
        tableCell('Complete', { bold: true, bg: 'e2e8f0' }),
        tableCell('Neg Float', { bold: true, bg: 'e2e8f0' }),
        tableCell('Days Behind', { bold: true, bg: 'e2e8f0' }),
        tableCell('Health', { bold: true, bg: 'e2e8f0' }),
        tableCell('Condition', { bold: true, bg: 'e2e8f0' }),
      ],
    }))

    trend.dataPoints.forEach(d => {
      // Data Date: real schedule date when available; mark fallback with parenthetical
      const dataDateText = d.dataDate
        ? shortDate(d.dataDate)
        : `${shortDate(d.uploadedAt)} (from upload)`
      dataRows.push(new TableRow({
        children: [
          tableCell(d.versionLabel, { bold: true }),
          tableCell(dataDateText, { color: d.dataDate ? undefined : COLOR_AMBER }),
          tableCell(shortDate(d.uploadedAt), { color: COLOR_GREY }),
          tableCell(String(d.totalActivities)),
          tableCell(`${d.completePct}%`),
          tableCell(String(d.negativeFloat), { color: d.negativeFloat > 50 ? COLOR_RED : undefined }),
          tableCell(`${d.delayDays > 0 ? '+' : ''}${d.delayDays}`, { color: d.delayDays > 30 ? COLOR_RED : d.delayDays > 0 ? COLOR_AMBER : COLOR_GREEN }),
          tableCell(`${d.healthScore}/100`),
          tableCell(d.condition),
        ],
      }))
    })

    children.push(new Table({
      rows: dataRows,
      width: { size: 100, type: WidthType.PERCENTAGE },
    }))

    children.push(new Paragraph({ spacing: { before: 240 }, children: [new TextRun({ text: '' })] }))

    // CHANGES BETWEEN VERSIONS
    children.push(heading('Major Changes Between Versions', HeadingLevel.HEADING_2))
    trend.changes.forEach(c => {
      children.push(para(`${c.fromVersion} → ${c.toVersion}  (${c.daysBetween} days apart)`, {
        bold: true, color: COLOR_PRIMARY, size: 22,
      }))
      if (c.majorChanges.length > 0) {
        c.majorChanges.forEach(m => children.push(bullet(m)))
      } else {
        children.push(para('No major changes detected — schedule remained stable', { italics: true, color: COLOR_GREY }))
      }
      children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: '' })] }))
    })

    // FOOTER NOTE
    children.push(new Paragraph({ children: [new PageBreak()] }))
    children.push(para('About This Report', { bold: true, size: 22 }))
    children.push(para(
      'This Trend Analysis Report was generated by NobelPM from the schedule versions uploaded by the user. ' +
      'All metrics are derived from the analyzed XER files. The NobelPM recommendation is provided as decision support and does not replace professional scheduler or project manager judgment.',
      { size: 18, color: COLOR_GREY }
    ))

    const doc = new Document({
      creator: 'NobelPM',
      title: `Trend Analysis - ${trend.projectName}`,
      sections: [{ children }],
    })

    const buffer = await Packer.toBuffer(doc)

    return new NextResponse(new Uint8Array(buffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="Trend_Analysis_${trend.projectName.replace(/[^a-z0-9]/gi, '_')}.docx"`,
      },
    })
  } catch (err: any) {
    console.error('Trend report error:', err)
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
